[project]
name = "scietex.logging"
description = "Asyncio logging handlers"
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICENSE"]
authors = [{ name = "Anton Bondarenko", email = "bond.anton@gmail.com" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]
dependencies = []
dynamic = ["version"]

[project.urls]
"Bug Tracker" = "https://github.com/bond-anton/scietex.logging/issues"
"Homepage" = "https://github.com/bond-anton/scietex.logging"

[project.optional-dependencies]
redis = ["redis>=5.0.0"]
valkey = ["valkey-glide~=2.5.0"]

# Specify multiple logging options combined
all = ["redis>=5.0.0", "valkey-glide~=2.5.0"]
dev = ["tox>=4.30.3", "redis>=5.0.0", "valkey-glide~=2.5.0"]
lint = ["ruff", "ty"]
test = ["pytest", "pytest-asyncio"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "scietex.logging.__version__" }

[tool.setuptools.package-data]
"scietex.logging" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]
