[tox]
env_list =
    format
    lint
    type
    py{314}

[testenv:format]
description = use ruff for formatting in a virtual environment
deps =
    ruff
commands =
    ruff format {posargs:.}

[testenv:lint]
description = run ruff checks on codebase
deps =
    ruff
    pytest>=7
    pytest-asyncio
commands =
    ruff check --fix {posargs:src tests examples}

[testenv:type]
description = run type checks on src
deps =
    ty
    redis>=5.0.0
    valkey-glide~=2.2.0
commands =
    ty check {posargs:src}

[testenv]
description = install pytest in a virtual environment and invoke it on the tests folder
deps =
    redis>=5.0.0
    valkey-glide~=2.2.0
    pytest>=7
    pytest-asyncio
    pytest-sugar
    coverage
extras = dev
commands = coverage erase
           coverage run -m pytest tests {posargs}
           coverage report --include="src/*" --omit="*test*"